In [1]:
import datetime as dt
import pandas as pd
import sys
sys.path.insert(0,"../../SigmaInvestments")
import Data_Retrieval as dr

In [3]:
data = pd.read_csv("../ProcessedPortfolio.csv")
start = dt.datetime(2020, 1, 1)
end = dt.datetime(2021, 9, 12)

In [4]:
conv = dict()
conv["XFRA"] = ".F"
conv["XAMS"] = ".AS"
conv["XPAR"] = ".PA"
conv["XLON"] = ".L"
conv["XDUB"] = ".IR"
conv["XHKG"] = ".HK"

data.loc[data["Ticker"]=="992", "Ticker"] = "0992"
for v in conv:
    data.loc[data["Exchange"]==v, "Ticker"] += conv[v]

data

,Sector,Company,Ticker,Exchange,Buying Date,Share Price,Target Price,Deviation from\n Target Price,Currency,Current in €,...,Total Return,Value Added,Weekly Return per Industry,Total Return per Industry,Market Cap,Market Cap in € (B),P/E ratio,Weight in Portofolio,Weight Industry,Optimization Weight (Risk Team)
0,Consumer Goods,Koninklijke Ahold Delhaize NV (XAMS:AD),AD.AS,XAMS,2020-10-16,26.7850,27.00,-0.007963,EUR,26.785000,...,0.117739,57.800000,-0.002391,-0.007392,28009740000,28.009740,12.0075,0.023752,0.138570,0.0250
1,Consumer Goods,"D.R. HORTON, INC. (XNYS:DHI)",DHI,XNYS,2021-02-23,70.9500,95.60,-0.257845,USD,73.219814,...,0.181706,232.535913,-0.002391,-0.007392,24817130000,25.611073,4.5574,0.035711,0.138570,0.0250
2,Consumer Goods,Kering SA (XPAR:KER),KER.PA,XPAR,2021-06-06,495.5000,765.00,-0.352288,EUR,495.500000,...,-0.152570,-418.400000,-0.002391,-0.007392,59552550000,59.552550,16.6685,0.043939,0.138570,0.0250
3,Consumer Goods,"LOWE'S COMPANIES, INC. (XNYS:LOW)",LOW,XNYS,2022-03-08,188.1200,259.52,-0.275123,USD,194.138287,...,-0.066573,-45.545139,-0.002391,-0.007392,116772400000,120.508153,14.8325,0.012912,0.138570,0.0250
4,Consumer Goods,"WARNER BROS. DISCOVERY, INC. (XNAS:WBD)",WBD,XNAS,2021-09-22,12.0100,54.22,-0.778495,USD,12.394221,...,-0.409518,-696.258111,-0.002391,-0.007392,28621320000,29.536966,7.2262,0.022256,0.138570,0.0250
5,Financial Services,MASTERCARD INCORPORATED. (XNYS:MA),MA,XNYS,2020-10-16,298.3600,345.00,-0.135188,USD,307.905057,...,0.044300,11.175057,-0.004398,0.000511,283708700000,292.785036,30.2385,0.006826,0.125353,0.0250
6,Financial Services,Allianz SE (XFRA:ALV),ALV.F,XFRA,2020-10-16,173.4400,227.00,-0.235947,EUR,173.440000,...,0.153084,40.000000,-0.004398,0.000511,68923180000,68.923180,17.9600,0.015380,0.125353,0.0250
7,Financial Services,S&P Global Inc. (XNYS:SPGI),SPGI,XNYS,2021-04-26,322.3700,425.00,-0.241482,USD,332.683179,...,0.043961,57.785893,-0.004398,0.000511,106006300000,109.397626,24.0215,0.036876,0.125353,0.0250
8,Financial Services,KKR & CO. INC. (XNYS:KKR),KKR,XNYS,2021-09-22,45.1100,77.51,-0.418011,USD,46.553148,...,-0.140865,-137.476491,-0.004398,0.000511,37738090000,38.945397,34.0468,0.017545,0.125353,0.0250
9,Financial Services,BARCLAYS PLC (XLON:BARC),BARC.L,XLON,2022-02-23,1.6626,2.11,-0.212038,GBp,1.863275,...,-0.188825,-181.677732,-0.004398,0.000511,25786050000,28.898409,5.5365,0.017184,0.125353,-1.0000
10,Financial Services,LONDON STOCK EXCHANGE GROUP PLC (XLON:LSEG),LSEG.L,XLON,2021-11-22,74.6800,90.28,-0.172796,GBp,83.693825,...,0.061810,51.745024,-0.004398,0.000511,41508040000,46.518032,46.3793,0.031542,0.125353,0.0632
11,Real Estate,"EQUINIX, INC. (XNAS:EQIX)",EQIX,XNAS,2020-11-30,609.2600,840.00,-0.274690,USD,628.751290,...,0.091396,122.133870,-0.000768,-0.000695,54019430000,55.747606,86.7325,0.041817,0.093249,0.0250
12,Real Estate,SL GREEN REALTY CORP. (XNYS:SLG),SLG,XNYS,2021-11-15,42.8600,94.27,-0.545348,USD,44.231166,...,-0.290030,-294.954840,-0.000768,-0.000695,2678770000,2.764469,9.6599,0.012747,0.093249,0.0250
13,Real Estate,"PROLOGIS, INC. (XNYS:PLD)",PLD,XNYS,2022-04-26,108.5400,190.34,-0.429757,USD,112.012384,...,-0.286025,-319.253313,-0.000768,-0.000695,80405050000,82.977348,21.6733,0.017382,0.093249,-1.0000
14,Real Estate,AMERICAN TOWER CORPORATION (XNYS:AMT),AMT,XNYS,2022-02-16,232.7800,288.39,-0.192829,USD,240.227038,...,0.194912,150.348153,-0.000768,-0.000695,106530900000,109.939009,38.2626,0.021302,0.093249,-1.0000
15,Healthcare,MEDTRONIC PUBLIC LIMITED COMPANY (XNYS:MDT),MDT,XNYS,2020-10-16,83.5600,130.00,-0.357231,USD,86.233230,...,-0.050637,-38.133849,-0.002596,0.062315,109867800000,113.382663,21.6076,0.009559,0.209172,0.0250
16,Healthcare,UNITEDHEALTH GROUP INCORPORATED (XNYS:UNH),UNH,XNYS,2020-11-30,517.4600,392.00,0.320051,USD,534.014448,...,0.914513,503.368896,-0.002596,0.062315,480421900000,495.791434,27.0311,0.023677,0.209172,0.0250
17,Healthcare,LABORATORY CORPORATION OF AMERICA HOLDINGS (XN...,LH,XNYS,2021-03-05,213.0300,313.00,-0.319393,USD,219.845201,...,0.111853,169.961610,-0.002596,0.062315,19134060000,19.746192,10.1982,0.038990,0.209172,0.0250
18,Healthcare,THERMO FISHER SCIENTIFIC INC. (XNYS:TMO),TMO,XNYS,2021-05-10,520.2900,553.00,-0.059150,USD,536.934985,...,0.404057,461.467454,-0.002596,0.062315,204039800000,210.567389,27.6777,0.035710,0.209172,0.1051
19,Healthcare,VERTEX PHARMACEUTICALS INCORPORATED (XNAS:VRTX),VRTX,XNAS,2021-05-13,286.3400,553.00,-0.059150,USD,295.500516,...,0.674256,357.011748,-0.002596,0.062315,72693440000,75.019030,23.1569,0.019653,0.209172,0.0250
20,Healthcare,"REGENERON PHARMACEUTICALS, INC. (XNAS:REGN)",REGN,XNAS,2021-10-25,688.2600,807.00,-0.147138,USD,710.278638,...,0.430715,427.657276,-0.002596,0.062315,76014770000,78.446615,13.7457,0.031492,0.209172,0.0250
21,Healthcare,"IDEXX LABORATORIES, INC. (XNAS:IDXX)",IDXX,XNAS,2022-03-08,326.0800,619.51,-0.473649,USD,336.511868,...,-0.294997,-140.808132,-0.002596,0.062315,27823390000,28.713509,42.1449,0.007460,0.209172,0.0250
22,Healthcare,"Teladoc Health, Inc. (XNYS:TDOC)",TDOC,XNYS,2022-05-06,27.9600,54.53,-0.487255,USD,28.854489,...,-0.095187,-75.887771,-0.002596,0.062315,4359911000,4.499392,0.0000,0.015992,0.209172,-1.0000
23,Healthcare,"HCA HEALTHCARE, INC. (XNYS:HCA)",HCA,XNYS,2021-11-29,194.0600,297.44,-0.347566,USD,200.268318,...,-0.027648,-40.450093,-0.002596,0.062315,54965250000,56.723684,9.3302,0.026639,0.209172,0.0250
24,Healthcare,"HCA HEALTHCARE, INC. (XNYS:HCA)",HCA,XNYS,2021-11-29,194.0600,297.44,-0.347566,USD,200.268318,...,-0.027648,-40.450093,-0.002596,0.062315,54965250000,56.723684,9.3302,0.026639,0.209172,-1.0000
25,Industrials,Deutsche Post AG (XFRA:DPW),DPW.F,XFRA,2020-10-16,31.5600,59.10,-0.465990,EUR,31.560000,...,-0.182630,-89.010000,-0.001347,-0.005274,37382420000,37.382420,7.1800,0.006297,0.095332,0.0250
26,Industrials,Magna International Inc. (XTSE:MG),MG,XTSE,2020-10-16,70.6800,85.00,-0.168471,CAD,53.675577,...,0.230630,75.662794,-0.001347,-0.005274,19812610000,15.046028,24.3000,0.010709,0.095332,0.0250
27,Industrials,E ON SE (XFRA:EOAN),EOAN.F,XFRA,2021-02-23,8.4060,12.00,-0.299500,EUR,8.406000,...,0.020820,-18.200000,-0.001347,-0.005274,21658810000,21.658810,6.1500,0.018635,0.095332,0.0250
28,Industrials,"APPLIED MATERIALS, INC. (XNAS:AMAT)",AMAT,XNAS,2021-06-06,85.0400,140.00,-0.392571,USD,87.760578,...,-0.268869,-166.797110,-0.001347,-0.005274,72515480000,74.835377,11.3797,0.009728,0.095332,0.0250
29,Industrials,CRH PUBLIC LIMITED COMPANY (XDUB:CRG),CRG.IR,XDUB,2021-05-12,33.9800,140.00,-0.392571,EUR,33.980000,...,-0.145041,-67.120000,-0.001347,-0.005274,22868170000,22.868170,15.5160,0.007533,0.095332,0.0250
30,Industrials,"AIR PRODUCTS AND CHEMICALS, INC. (XNYS:APD)",APD,XNYS,2021-11-29,238.5200,333.74,-0.285312,USD,246.150671,...,-0.047877,-78.146646,-0.001347,-0.005274,52581880000,54.264066,23.7841,0.027285,0.095332,0.0250
31,Industrials,LOUISIANA-PACIFIC CORPORATION (XNYS:LPX),LPX,XNYS,2022-02-16,50.9200,114.42,-0.554973,USD,52.549020,...,-0.129939,-108.562745,-0.001347,-0.005274,3669963000,3.787372,3.2933,0.015145,0.095332,-1.0000
32,Technology,Deutsche Telekom AG (XFRA:DTE),DTE.F,XFRA,2020-10-16,18.6120,20.00,-0.069400,EUR,18.612000,...,0.420537,514.707000,-0.002038,-0.004833,91331980000,91.331980,13.6300,0.045800,0.236187,0.0250
33,Technology,"NETFLIX, INC. (XNAS:NFLX)",NFLX,XNAS,2020-10-16,237.0500,576.00,-0.588455,USD,244.633643,...,-0.490134,-705.499993,-0.002038,-0.004833,100685800000,103.906914,22.1823,0.016270,0.236187,0.0250
34,Technology,EATON CORPORATION PUBLIC LIMITED COMPANY (XNYS...,ETN,XNYS,2020-10-16,135.1300,120.00,0.126083,USD,139.453044,...,0.538144,454.130444,-0.002038,-0.004833,53427960000,55.137214,23.4643,0.030915,0.236187,0.0250
35,Technology,NVIDIA CORPORATION (XNAS:NVDA),NVDA,XNAS,2020-10-16,125.6100,137.25,-0.084809,USD,129.628483,...,0.083967,29.035449,-0.002038,-0.004833,311648400000,321.618576,41.1870,0.008621,0.236187,0.0580
36,Technology,SAP SE (XFRA:SAPA),SAPA.F,XFRA,2021-02-23,83.0000,128.00,-0.351562,EUR,83.000000,...,-0.165305,-74.400000,-0.002038,-0.004833,97949730000,97.949730,24.3900,0.007360,0.236187,0.0250
37,Technology,Tencent Holdings Limited (OTCM:TCEHY),TCEHY,OTCM,2021-09-24,35.7000,100.72,-0.645552,USD,36.842105,...,-0.240089,-239.182105,-0.002038,-0.004833,2638864000000,2723.285862,19.5800,0.014702,0.236187,0.0250
38,Technology,ALPHABET INC. (XNAS:GOOG),GOOG,XNAS,2021-09-30,100.5700,216.12,-0.534657,USD,103.787410,...,-0.245182,-674.251806,-0.002038,-0.004833,1290615000000,1331.904025,18.7071,0.046017,0.236187,0.0250
39,Technology,Lenovo Group Limited (XHKG:992),0992.HK,XHKG,2021-09-28,5.9000,13.39,-0.559373,HKD,0.775703,...,-0.125316,-328.593216,-0.002038,-0.004833,71192130000,9.359996,4.2000,0.034393,0.236187,0.0548
40,Technology,"Meta Platforms, Inc. (XNAS:META)",META,XNAS,2021-11-22,142.8200,439.37,-0.674944,USD,147.389061,...,-0.525241,-815.304696,-0.002038,-0.004833,377358700000,389.431063,11.8398,0.016337,0.236187,0.0411
41,Technology,DELL TECHNOLOGIES INC. (XNYS:DELL),DELL,XNYS,2022-02-11,36.2800,69.80,-0.480229,USD,37.440660,...,-0.289155,-301.327451,-0.002038,-0.004833,26034740000,26.867637,4.8866,0.015770,0.236187,0.0250

In [5]:
tickers = data["Ticker"].tolist()
source = 'yahoo'
closes = dr.stock_adjusted_closes(tickers, source, start, end)
nofind = closes.columns[closes.isna().all()].tolist()
print("Could not find: ",nofind)

closes

Could not find:  []

Symbols         AD.AS
Date
2020-01-02  20.366858
2020-01-03  20.232216
2020-01-06  20.232216
2020-01-07  20.160404
2020-01-08  20.048203
...               ...
2021-09-06  27.382227
2021-09-07  27.261538
2021-09-08  27.507744
2021-09-09  27.295330
2021-09-10  26.923603

[435 rows x 1 columns]

In [6]:
closes.reset_index().to_csv("../stocks-"+start.strftime("%Y_%m_%d")+"-"+end.strftime("%Y_%m_%d")+".csv", index=False)